# Generated by Django 2.1.7 on 2019-05-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_userinfo_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
